"use client";
import Navbar from "./components/navbar/Navbar";
import About from "./components/About";
import Project from "./components/Projects";
import Stack from "./components/navbar/stackSection/Stack";
import Head from "next/head";
import Contact from "./components/Contact";
import ContactHome from "./components/ContactHome";
import { motion } from "framer-motion";
import Background from "./components/ui/backGround";

// Definición del componente Home
export default function Home() {
  return (
    <>
      {/* Encabezado de la página */}
      
      <Head>
        <title>My portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      {/* Barra de navegación */}
      <Navbar />

      {/* Sección de contacto en la página principal */}
      <ContactHome />

      {/* Sección "About" */}
      <section className="flex my-4" id="About">
        <motion.div
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, amount: 0.5 }}
          transition={{ delay: 0.5, duration: 0.5 }}
          variants={{
            hidden: { opacity: 0, y: 50 },
            visible: { opacity: 1, y: 0 },
          }}
          className="h-[28rem] md:h-[25rem] rounded-3xl p-7 lg:h-[22rem] flex flex-col shadow-box colorBg"
        >
          <About />
        </motion.div>
      </section>

      {/* Sección "Stack" */}
      <motion.section
        initial="hidden"
        whileInView="visible"
        viewport={{ once: true, amount: 0.5 }}
        transition={{ delay: 0.3, duration: 0.5 }}
        variants={{
          hidden: { opacity: 0, y: 50 },
          visible: { opacity: 1, y: 0 },
        }}
        className="h-[33rem] md:h-[16rem] rounded-3xl  shadow-box grid items-center  colorBg"
        id="Stack"
      >
        <div>
          {/* Contenido de la sección Stack */}
          <Stack />
        </div>
      </motion.section>

      {/* Sección "Projects" */}
      <section
        className="grid grid-cols-1 lg:grid-cols-2 my-14 gap-4"
        id="Projects"
      >
        {/* Contenido de la sección Projects */}
        <motion.div
         initial="hidden"
         whileInView="visible"
         viewport={{once:true ,amount:0.5}}
         transition={{delay:0.2,duration:0.5}}
         variants={{
           hidden:{opacity:0 ,y: 50},
           visible:{opacity:1 , y:0},
          }}
        >
          <Project
            name="Stookkicks"
            imgUrl="/project-1.png"
            description="sneaker blog"
            bgColor="#fff"
            urlLink="https://fanciful-mousse-4580db.netlify.app/"
            gitLink="https://github.com/julianvidela/Stoock.github.io.git"
            
          />
        </motion.div>
          <motion.div
           initial="hidden"
           whileInView="visible"
           viewport={{once:true ,amount:0.5}}
           transition={{delay:0.3,duration:0.5}}
           variants={{
             hidden:{opacity:0 ,y: 50},
            visible:{opacity:1 , y:0},
          }}
          >
            <Project
              name="AI Decor"
              imgUrl="/project-3.png"
              description="Ai Image Generator"
              bgColor="#fff"
              urlLink="https://ai-decor.vercel.app/"
              gitLink="https://github.com/julianvidela/AI-decor.git"
              
            />
          </motion.div>
          <motion.div
           initial="hidden"
           whileInView="visible"
           viewport={{once:true ,amount:0.5}}
           transition={{delay:0.4,duration:0.5}}
           variants={{
            hidden:{opacity:0 ,y: 50},
            visible:{opacity:1 , y:0},
           }}
          >
            <Project
              name="Portfolio"
              imgUrl="/project-2.png"
              description="personal porfolio web"
              bgColor="#fff"
              urlLink="https://julianvidela.vercel.app/"
              gitLink="https://github.com/julianvidela/portfolio3.0.git"
            />
          </motion.div>
      </section>

      {/* Sección de contacto */}
     
      

      <Contact />
     
    </>
  );
}
