// Importa las bibliotecas y componentes necesarios
import React from "react";
import Navbar from "./components/navbar/Navbar";
import About from "./components/About";
import Project from "./components/Projects";
import Stack from "./components/navbar/stackSection/Stack";
import Head from "next/head"; // Importa el componente Head de next/head
import Contact from "./components/Contact";
import ContactHome from "./components/ContactHome";


// Definición del componente Home
export default function Home() {
  return (
    <>
      {/* Encabezado de la página */}
      <Head>
        <title>My portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      {/* Barra de navegación */}
      <Navbar />

      {/* Sección de contacto en la página principal */}
      <ContactHome />

      {/* Sección "About" */}
      <section className="flex my-4" id="About">
        <div className="h-[34rem] md:h-[25rem] rounded-3xl p-7 lg:h-[22rem] flex flex-col shadow-box colorBg">
          <About />
        </div>
      </section>

      {/* Sección "Stack" */}
      <section
        className="h-[33rem] md:h-[16rem] rounded-3xl p-6 mb-4 shadow-box grid items-center colorBg"
        id="Stack"
      >
        <div>
          {/* Contenido de la sección Stack */}
          <Stack />
        </div>
      </section>

      {/* Sección "Projects" */}
      <section
        className="grid grid-cols-1 lg:grid-cols-2 my-4 gap-4"
        id="Projects"
      >
        {/* Contenido de la sección Projects */}
        <Project
          name="Portfolio"
          imgUrl="/project-2.png"
          description="personal porfolio web"
          bgColor="#fff"
          urlLink="https://julianvidela.vercel.app/"
          gitLink="https://github.com/julianvidela/portfolio3.0.git"
          
        />
        <Project
          name="Stookkicks"
          imgUrl="/project-1.png"
          description="sneaker blog"
          bgColor="#fff"
          urlLink="https://fanciful-mousse-4580db.netlify.app/"
          gitLink="https://github.com/julianvidela/Stoock.github.io.git"
          

        />


      </section>

      {/* Sección de contacto */}
      <Contact />
    </>
  );
}
